import type { MetricCardItem, DrillDownRecord, FunnelStep, WishlistProject } from './types';

// =========================================================================
// METRIC CARDS DATA
// =========================================================================

export const METRIC_CARDS: MetricCardItem[] = [
  {
    id: 'total_properties',
    index: 1,
    category: 'PROPERTIES',
    label: 'Total Properties',
    value: 10,
    sub: 'Created',
    change: '14.2%',
    isPositive: true,
    filterDescription: 'All cataloged property assets currently managed in the master inventory database',
  },
  {
    id: 'sale_properties',
    index: 2,
    category: 'PROPERTIES',
    label: 'Sale Properties',
    value: 7,
    sub: 'Created',
    change: '12.5%',
    isPositive: true,
    filterDescription: 'Properties zoned and listed for direct freehold/leasehold capital acquisition',
  },
  {
    id: 'lease_properties',
    index: 3,
    category: 'PROPERTIES',
    label: 'Lease Properties',
    value: 3,
    sub: 'Created',
    change: '18%',
    isPositive: true,
    filterDescription: 'Rental residential & commercial units available for long/short-term tenancy',
  },
  {
    id: 'approved_properties',
    index: 4,
    category: 'PROPERTIES',
    label: 'Approved Properties',
    value: 6,
    sub: 'Created',
    change: '9.4%',
    isPositive: true,
    filterDescription: 'Verified properties that have cleared municipal & compliance verification',
  },
  {
    id: 'pending_properties',
    index: 5,
    category: 'PROPERTIES',
    label: 'Pending Properties',
    value: 3,
    sub: 'Created',
    change: '4.2%',
    isPositive: false,
    filterDescription: 'Properties awaiting documentation verification, title audit, or owner confirmation',
  },
  {
    id: 'total_projects',
    index: 6,
    category: 'PROJECTS',
    label: 'Total Projects',
    value: 7,
    sub: 'Created',
    change: '8.6%',
    isPositive: true,
    filterDescription: 'Masterplanned developments and multi-phase residential communities in pipeline',
  },
  {
    id: 'total_lead_list',
    index: 7,
    category: 'LEADS',
    label: 'Total Lead List',
    value: 10,
    sub: 'Created',
    change: '22.4%',
    isPositive: true,
    filterDescription: 'Prospective buyers and investors registered during the current active campaign',
  },
  {
    id: 'booking_inquiries',
    index: 8,
    category: 'LEADS',
    label: 'Booking Inquiries',
    value: 4,
    sub: 'Booking Appointment',
    change: '16.8%',
    isPositive: true,
    filterDescription: 'Prospects who confirmed an on-site walkthrough or VIP preview session',
  },
  {
    id: 'call_inquiries',
    index: 9,
    category: 'LEADS',
    label: 'Call Inquiries',
    value: 2,
    sub: 'Created',
    change: '11.2%',
    isPositive: true,
    filterDescription: 'Inbound phone queries and voice discussions logged by the central brokerage desk',
  },
  {
    id: 'deal_won',
    index: 10,
    category: 'DEALS',
    label: 'Deal Won',
    value: 2,
    sub: 'Status',
    change: '24.5%',
    isPositive: true,
    filterDescription: 'Successfully finalized sale deed agreements and executed deposit transfers',
  },
  {
    id: 'deal_lost',
    index: 11,
    category: 'DEALS',
    label: 'Deal Lost',
    value: 2,
    sub: 'Status',
    change: '8.1%',
    isPositive: false,
    filterDescription: 'Cancelled buyer negotiations or contracts dropped before token clearance',
  },
  {
    id: 'follow_ups',
    index: 12,
    category: 'LEADS',
    label: 'Follow Ups',
    value: 2,
    sub: 'Status',
    change: '15.3%',
    isPositive: true,
    filterDescription: 'Scheduled agent engagements, term-sheet reconciliations, and payment reminders',
  },
  {
    id: 'conversion_rate',
    index: 13,
    category: 'PROJECTS',
    label: 'Lead Conversion Rate',
    value: '8.1%',
    sub: 'Project List with Conver...',
    change: '3.8%',
    isPositive: true,
    filterDescription: 'Comprehensive lead-to-closure velocity across active project sales galleries',
  },
  {
    id: 'high_demand_projects',
    index: 14,
    category: 'DEMAND',
    label: 'High Demand Projects',
    value: 4,
    sub: 'Created (Top Inquiries &...)',
    change: '25%',
    isPositive: true,
    // highlight: true,
    filterDescription: 'Created Date Filter (Top Inquiries & Leads) — Developments exceeding baseline lead & booking targets',
  },
  {
    id: 'low_demand_projects',
    index: 15,
    category: 'DEMAND',
    label: 'Low Demand Projects',
    value: 3,
    sub: 'Created (Needs Market...)',
    change: '12%',
    isPositive: false,
    filterDescription: 'Developments trailing inquiry benchmarks requiring targeted promotional syndication',
  },
];

// =========================================================================
// DRILL DOWN DATASETS
// =========================================================================

export const DRILL_DOWN_DATASETS: Record<string, DrillDownRecord[]> = {
  high_demand_projects: [
    {
      id: 'HDP-1',
      name: 'The Sovereign Sky Residences',
      developer: 'Vanguard Realty Group',
      location: 'Downtown Financial Hub',
      priceRange: '$850.0K - $3.40M',
      priceAvg: 'Avg $1120/sq.ft',
      callbacks: 195,
      bookingInquiries: 112,
      totalLeads: 418,
      demandScore: 96,
      status: 'Under Construction',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'HDP-2',
      name: 'Azure Marina Waterfront',
      developer: 'Apex Waterfront Estates',
      location: 'Marina Bay Promenade',
      priceRange: '$1.20M - $5.80M',
      priceAvg: 'Avg $1450/sq.ft',
      callbacks: 260,
      bookingInquiries: 148,
      totalLeads: 560,
      demandScore: 98,
      status: 'Under Construction',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'HDP-3',
      name: 'Highland Serenade Villas',
      developer: 'Elysian Living Corp',
      location: 'Highland Hills',
      priceRange: '$2.10M - $6.50M',
      priceAvg: 'Avg $980/sq.ft',
      callbacks: 140,
      bookingInquiries: 86,
      totalLeads: 310,
      demandScore: 91,
      status: 'Ready to Move',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'HDP-4',
      name: 'Nexus Silicon Tech Enclave',
      developer: 'InnoUrban Developments',
      location: 'Tech Corridor Innovation District',
      priceRange: '$420.0K - $1.10M',
      priceAvg: 'Avg $780/sq.ft',
      callbacks: 220,
      bookingInquiries: 125,
      totalLeads: 490,
      demandScore: 88,
      status: 'Under Construction',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    },
  ],
  total_properties: [
    {
      id: 'PROP-101',
      name: 'Skyline Penthouse 42B',
      developer: 'Vanguard Realty Group',
      location: 'Downtown Financial Hub',
      priceRange: '$2.80M - $3.40M',
      priceAvg: 'Avg $1280/sq.ft',
      callbacks: 48,
      bookingInquiries: 24,
      totalLeads: 88,
      demandScore: 94,
      status: 'Approved',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PROP-102',
      name: 'Azure Marina Ocean Villa 7',
      developer: 'Apex Waterfront Estates',
      location: 'Marina Bay Promenade',
      priceRange: '$4.50M - $5.80M',
      priceAvg: 'Avg $1560/sq.ft',
      callbacks: 62,
      bookingInquiries: 38,
      totalLeads: 115,
      demandScore: 97,
      status: 'Approved',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PROP-103',
      name: 'Highland Serenade Manor 12',
      developer: 'Elysian Living Corp',
      location: 'Highland Hills',
      priceRange: '$3.20M - $4.10M',
      priceAvg: 'Avg $1040/sq.ft',
      callbacks: 34,
      bookingInquiries: 19,
      totalLeads: 62,
      demandScore: 90,
      status: 'Ready to Move',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PROP-104',
      name: 'Nexus Smart Studio Suite 405',
      developer: 'InnoUrban Developments',
      location: 'Tech Corridor Innovation District',
      priceRange: '$420.0K - $560.0K',
      priceAvg: 'Avg $820/sq.ft',
      callbacks: 55,
      bookingInquiries: 31,
      totalLeads: 94,
      demandScore: 89,
      status: 'Under Construction',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PROP-105',
      name: 'Uptown Royale Duplex 18',
      developer: 'Royal Palm Holdings',
      location: 'Uptown Central Avenue',
      priceRange: '$1.40M - $1.90M',
      priceAvg: 'Avg $940/sq.ft',
      callbacks: 28,
      bookingInquiries: 14,
      totalLeads: 46,
      demandScore: 78,
      status: 'Approved',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PROP-106',
      name: 'Heritage Stone Eco Cottage 3',
      developer: 'Greenstone Developers',
      location: 'Greenwood Valley Reserve',
      priceRange: '$650.0K - $820.0K',
      priceAvg: 'Avg $680/sq.ft',
      callbacks: 18,
      bookingInquiries: 8,
      totalLeads: 29,
      demandScore: 68,
      status: 'Pending Review',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PROP-107',
      name: 'Eastgate Logistics Hub Unit 9',
      developer: 'Apex Infrastructure Group',
      location: 'Eastgate Commercial Parkway',
      priceRange: '$1.10M - $1.60M',
      priceAvg: 'Avg $520/sq.ft',
      callbacks: 14,
      bookingInquiries: 6,
      totalLeads: 22,
      demandScore: 61,
      status: 'Pending Review',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PROP-108',
      name: 'Solaria Crest Townhouse 5',
      developer: 'Solaria Buildcon',
      location: 'Solaria Foothills',
      priceRange: '$780.0K - $990.0K',
      priceAvg: 'Avg $720/sq.ft',
      callbacks: 22,
      bookingInquiries: 11,
      totalLeads: 37,
      demandScore: 74,
      status: 'Approved',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PROP-109',
      name: 'Grand Horizon Commercial Suite',
      developer: 'Horizon Capital Real Estate',
      location: 'Downtown Financial Hub',
      priceRange: '$1.80M - $2.50M',
      priceAvg: 'Avg $1150/sq.ft',
      callbacks: 30,
      bookingInquiries: 15,
      totalLeads: 52,
      demandScore: 82,
      status: 'Approved',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PROP-110',
      name: 'Pinecrest Luxury Chalet',
      developer: 'Alpine Retreat Living',
      location: 'Pinecrest Ridge',
      priceRange: '$1.95M - $2.70M',
      priceAvg: 'Avg $920/sq.ft',
      callbacks: 19,
      bookingInquiries: 9,
      totalLeads: 33,
      demandScore: 70,
      status: 'Pending Review',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=120&auto=format&fit=crop&q=80',
    },
  ],
  sale_properties: [
    {
      id: 'SALE-1',
      name: 'The Sovereign Sky Penthouse',
      developer: 'Vanguard Realty Group',
      location: 'Downtown Financial Hub',
      priceRange: '$2.80M - $3.40M',
      priceAvg: 'Avg $1280/sq.ft',
      callbacks: 65,
      bookingInquiries: 38,
      totalLeads: 140,
      demandScore: 96,
      status: 'Approved for Sale',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'SALE-2',
      name: 'Azure Marina Grand Beach Villa',
      developer: 'Apex Waterfront Estates',
      location: 'Marina Bay Promenade',
      priceRange: '$4.50M - $5.80M',
      priceAvg: 'Avg $1560/sq.ft',
      callbacks: 82,
      bookingInquiries: 49,
      totalLeads: 185,
      demandScore: 98,
      status: 'Approved for Sale',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'SALE-3',
      name: 'Highland Serenade Villa 8',
      developer: 'Elysian Living Corp',
      location: 'Highland Hills',
      priceRange: '$2.10M - $3.20M',
      priceAvg: 'Avg $980/sq.ft',
      callbacks: 44,
      bookingInquiries: 28,
      totalLeads: 95,
      demandScore: 92,
      status: 'Ready to Move',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'SALE-4',
      name: 'Nexus Tech 3-BHK Smart Condo',
      developer: 'InnoUrban Developments',
      location: 'Tech Corridor Innovation District',
      priceRange: '$850.0K - $1.10M',
      priceAvg: 'Avg $880/sq.ft',
      callbacks: 70,
      bookingInquiries: 42,
      totalLeads: 160,
      demandScore: 89,
      status: 'Under Construction',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'SALE-5',
      name: 'Uptown Royale Royal Duplex',
      developer: 'Royal Palm Holdings',
      location: 'Uptown Central Avenue',
      priceRange: '$1.40M - $1.90M',
      priceAvg: 'Avg $940/sq.ft',
      callbacks: 32,
      bookingInquiries: 18,
      totalLeads: 58,
      demandScore: 80,
      status: 'Approved for Sale',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'SALE-6',
      name: 'Solaria Crest Townhouse',
      developer: 'Solaria Buildcon',
      location: 'Solaria Foothills',
      priceRange: '$780.0K - $990.0K',
      priceAvg: 'Avg $720/sq.ft',
      callbacks: 26,
      bookingInquiries: 15,
      totalLeads: 48,
      demandScore: 76,
      status: 'Approved for Sale',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'SALE-7',
      name: 'Grand Horizon Executive Suite',
      developer: 'Horizon Capital Real Estate',
      location: 'Downtown Financial Hub',
      priceRange: '$1.80M - $2.50M',
      priceAvg: 'Avg $1150/sq.ft',
      callbacks: 38,
      bookingInquiries: 22,
      totalLeads: 70,
      demandScore: 84,
      status: 'Approved for Sale',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=120&auto=format&fit=crop&q=80',
    },
  ],
  lease_properties: [
    {
      id: 'LEASE-1',
      name: 'Nexus Innovation Co-Work Suite',
      developer: 'InnoUrban Developments',
      location: 'Tech Corridor Innovation District',
      priceRange: '$8,500/mo ($102K/yr)',
      priceAvg: 'Term: 36 Months',
      callbacks: 45,
      bookingInquiries: 25,
      totalLeads: 80,
      demandScore: 88,
      status: 'Active Lease',
      statusType: 'info',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEASE-2',
      name: 'The Sovereign Corporate Lounge',
      developer: 'Vanguard Realty Group',
      location: 'Downtown Financial Hub',
      priceRange: '$14,200/mo ($170K/yr)',
      priceAvg: 'Term: 24 Months',
      callbacks: 32,
      bookingInquiries: 18,
      totalLeads: 55,
      demandScore: 91,
      status: 'Active Lease',
      statusType: 'info',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEASE-3',
      name: 'Eastgate Logistics Cargo Bay 4',
      developer: 'Apex Infrastructure Group',
      location: 'Eastgate Commercial Parkway',
      priceRange: '$6,800/mo ($81.6K/yr)',
      priceAvg: 'Term: 60 Months',
      callbacks: 19,
      bookingInquiries: 9,
      totalLeads: 31,
      demandScore: 65,
      status: 'Under Review',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=120&auto=format&fit=crop&q=80',
    },
  ],
  approved_properties: [
    {
      id: 'APPR-1',
      name: 'The Sovereign Sky Tower A',
      developer: 'Vanguard Realty Group',
      location: 'Downtown Financial Hub',
      priceRange: '$850.0K - $3.40M',
      priceAvg: 'Avg $1120/sq.ft',
      callbacks: 195,
      bookingInquiries: 112,
      totalLeads: 418,
      demandScore: 96,
      status: 'Municipal Clearance OK',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'APPR-2',
      name: 'Azure Marina Waterfront Luxury',
      developer: 'Apex Waterfront Estates',
      location: 'Marina Bay Promenade',
      priceRange: '$1.20M - $5.80M',
      priceAvg: 'Avg $1450/sq.ft',
      callbacks: 260,
      bookingInquiries: 148,
      totalLeads: 560,
      demandScore: 98,
      status: 'RERA Approved',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'APPR-3',
      name: 'Highland Serenade Villas Phase 1',
      developer: 'Elysian Living Corp',
      location: 'Highland Hills',
      priceRange: '$2.10M - $6.50M',
      priceAvg: 'Avg $980/sq.ft',
      callbacks: 140,
      bookingInquiries: 86,
      totalLeads: 310,
      demandScore: 91,
      status: 'Title Verified',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'APPR-4',
      name: 'Nexus Silicon Tech Enclave',
      developer: 'InnoUrban Developments',
      location: 'Tech Corridor Innovation District',
      priceRange: '$420.0K - $1.10M',
      priceAvg: 'Avg $780/sq.ft',
      callbacks: 220,
      bookingInquiries: 125,
      totalLeads: 490,
      demandScore: 88,
      status: 'Zoning Approved',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'APPR-5',
      name: 'Uptown Royale Boulevard Residences',
      developer: 'Royal Palm Holdings',
      location: 'Uptown Central Avenue',
      priceRange: '$950.0K - $2.20M',
      priceAvg: 'Avg $910/sq.ft',
      callbacks: 95,
      bookingInquiries: 48,
      totalLeads: 180,
      demandScore: 81,
      status: 'License Active',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'APPR-6',
      name: 'Solaria Crest Modern Villas',
      developer: 'Solaria Buildcon',
      location: 'Solaria Foothills',
      priceRange: '$780.0K - $1.35M',
      priceAvg: 'Avg $720/sq.ft',
      callbacks: 88,
      bookingInquiries: 42,
      totalLeads: 155,
      demandScore: 77,
      status: 'Approved',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=120&auto=format&fit=crop&q=80',
    },
  ],
  pending_properties: [
    {
      id: 'PEND-1',
      name: 'Heritage Stone Eco Village Phase 2',
      developer: 'Greenstone Developers',
      location: 'Greenwood Valley Reserve',
      priceRange: '$650.0K - $1.40M',
      priceAvg: 'Avg $640/sq.ft',
      callbacks: 54,
      bookingInquiries: 22,
      totalLeads: 94,
      demandScore: 66,
      status: 'Awaiting Environmental Clearance',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PEND-2',
      name: 'Eastgate Logistics Hub Commercial',
      developer: 'Apex Infrastructure Group',
      location: 'Eastgate Commercial Parkway',
      priceRange: '$1.10M - $2.80M',
      priceAvg: 'Avg $520/sq.ft',
      callbacks: 42,
      bookingInquiries: 18,
      totalLeads: 82,
      demandScore: 59,
      status: 'Zoning Audit In Progress',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PEND-3',
      name: 'Pinecrest Alpine Chalets',
      developer: 'Alpine Retreat Living',
      location: 'Pinecrest Ridge',
      priceRange: '$1.95M - $3.20M',
      priceAvg: 'Avg $920/sq.ft',
      callbacks: 36,
      bookingInquiries: 14,
      totalLeads: 68,
      demandScore: 64,
      status: 'Fire Safety Sign-off Pending',
      statusType: 'danger',
      image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=120&auto=format&fit=crop&q=80',
    },
  ],
  total_projects: [
    {
      id: 'PRJ-1',
      name: 'The Sovereign Sky Residences',
      developer: 'Vanguard Realty Group',
      location: 'Downtown Financial Hub',
      priceRange: '$850.0K - $3.40M',
      priceAvg: 'Avg $1120/sq.ft',
      callbacks: 195,
      bookingInquiries: 112,
      totalLeads: 418,
      demandScore: 96,
      status: 'Active Launch (Phase 2)',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PRJ-2',
      name: 'Azure Marina Waterfront',
      developer: 'Apex Waterfront Estates',
      location: 'Marina Bay Promenade',
      priceRange: '$1.20M - $5.80M',
      priceAvg: 'Avg $1450/sq.ft',
      callbacks: 260,
      bookingInquiries: 148,
      totalLeads: 560,
      demandScore: 98,
      status: 'Active Launch (Phase 1)',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PRJ-3',
      name: 'Highland Serenade Villas',
      developer: 'Elysian Living Corp',
      location: 'Highland Hills',
      priceRange: '$2.10M - $6.50M',
      priceAvg: 'Avg $980/sq.ft',
      callbacks: 140,
      bookingInquiries: 86,
      totalLeads: 310,
      demandScore: 91,
      status: 'Handover Ready',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PRJ-4',
      name: 'Nexus Silicon Tech Enclave',
      developer: 'InnoUrban Developments',
      location: 'Tech Corridor Innovation District',
      priceRange: '$420.0K - $1.10M',
      priceAvg: 'Avg $780/sq.ft',
      callbacks: 220,
      bookingInquiries: 125,
      totalLeads: 490,
      demandScore: 88,
      status: 'Construction 65%',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PRJ-5',
      name: 'Uptown Royale Boulevard',
      developer: 'Royal Palm Holdings',
      location: 'Uptown Central Avenue',
      priceRange: '$950.0K - $2.20M',
      priceAvg: 'Avg $910/sq.ft',
      callbacks: 110,
      bookingInquiries: 52,
      totalLeads: 210,
      demandScore: 81,
      status: 'Foundation Complete',
      statusType: 'info',
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PRJ-6',
      name: 'Heritage Stone Eco Village',
      developer: 'Greenstone Developers',
      location: 'Greenwood Valley Reserve',
      priceRange: '$650.0K - $1.40M',
      priceAvg: 'Avg $640/sq.ft',
      callbacks: 54,
      bookingInquiries: 22,
      totalLeads: 94,
      demandScore: 66,
      status: 'Pre-launch Stage',
      statusType: 'neutral',
      image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'PRJ-7',
      name: 'Eastgate Logistics & Cargo Hub',
      developer: 'Apex Infrastructure Group',
      location: 'Eastgate Commercial Parkway',
      priceRange: '$1.10M - $2.80M',
      priceAvg: 'Avg $520/sq.ft',
      callbacks: 42,
      bookingInquiries: 18,
      totalLeads: 82,
      demandScore: 59,
      status: 'Structural Steel Stage',
      statusType: 'neutral',
      image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=120&auto=format&fit=crop&q=80',
    },
  ],
  total_lead_list: [
    {
      id: 'LEAD-101',
      name: 'Arthur Sterling (Family Office)',
      developer: 'Target: Azure Marina Waterfront',
      location: 'Marina Bay Promenade',
      priceRange: 'Budget: $4.5M - $6.0M',
      priceAvg: 'Source: Website Direct',
      callbacks: 4,
      bookingInquiries: 2,
      totalLeads: 1,
      demandScore: 98,
      status: 'Active VIP Buyer',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEAD-102',
      name: 'Elena Rostova (Tech Executive)',
      developer: 'Target: Nexus Silicon Tech Enclave',
      location: 'Tech Corridor Innovation District',
      priceRange: 'Budget: $900K - $1.2M',
      priceAvg: 'Source: Referral',
      callbacks: 3,
      bookingInquiries: 1,
      totalLeads: 1,
      demandScore: 95,
      status: 'Term Sheet Sent',
      statusType: 'info',
      image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEAD-103',
      name: 'Marcus & Sophia Vance',
      developer: 'Target: Highland Serenade Villas',
      location: 'Highland Hills',
      priceRange: 'Budget: $2.5M - $3.2M',
      priceAvg: 'Source: Walk-in Gallery',
      callbacks: 5,
      bookingInquiries: 3,
      totalLeads: 1,
      demandScore: 92,
      status: 'Deposit Pending',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEAD-104',
      name: 'David K. Henderson',
      developer: 'Target: The Sovereign Sky Residences',
      location: 'Downtown Financial Hub',
      priceRange: 'Budget: $1.8M - $2.2M',
      priceAvg: 'Source: Property Portal',
      callbacks: 2,
      bookingInquiries: 1,
      totalLeads: 1,
      demandScore: 89,
      status: 'Site Visit Completed',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEAD-105',
      name: 'Amira Al-Mansoor (Global Fund)',
      developer: 'Target: Azure Marina Bulk Units',
      location: 'Marina Bay Promenade',
      priceRange: 'Budget: $12.0M Institutional',
      priceAvg: 'Source: Broker Network',
      callbacks: 6,
      bookingInquiries: 2,
      totalLeads: 1,
      demandScore: 99,
      status: 'Contract Drafting',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEAD-106',
      name: 'Chen Wei & Li Na',
      developer: 'Target: Uptown Royale Boulevard',
      location: 'Uptown Central Avenue',
      priceRange: 'Budget: $1.1M - $1.4M',
      priceAvg: 'Source: Social Media',
      callbacks: 2,
      bookingInquiries: 1,
      totalLeads: 1,
      demandScore: 82,
      status: 'Call Follow-up',
      statusType: 'info',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEAD-107',
      name: 'Robert C. Thorne',
      developer: 'Target: Heritage Stone Eco Village',
      location: 'Greenwood Valley Reserve',
      priceRange: 'Budget: $700K - $850K',
      priceAvg: 'Source: Print Ad',
      callbacks: 1,
      bookingInquiries: 0,
      totalLeads: 1,
      demandScore: 71,
      status: 'Pre-qualified',
      statusType: 'neutral',
      image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEAD-108',
      name: 'Dr. Evelyn Martinez',
      developer: 'Target: The Sovereign Sky Residences',
      location: 'Downtown Financial Hub',
      priceRange: 'Budget: $1.5M - $2.0M',
      priceAvg: 'Source: Referral',
      callbacks: 3,
      bookingInquiries: 1,
      totalLeads: 1,
      demandScore: 91,
      status: 'Negotiation',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEAD-109',
      name: 'Vikram & Priya Malhotra',
      developer: 'Target: Nexus Silicon Tech Enclave',
      location: 'Tech Corridor Innovation District',
      priceRange: 'Budget: $850K - $1.0M',
      priceAvg: 'Source: Website Direct',
      callbacks: 4,
      bookingInquiries: 2,
      totalLeads: 1,
      demandScore: 88,
      status: 'Financing Review',
      statusType: 'info',
      image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LEAD-110',
      name: 'Jonathan Reynolds',
      developer: 'Target: Eastgate Logistics Hub',
      location: 'Eastgate Commercial Parkway',
      priceRange: 'Budget: $1.8M Commercial',
      priceAvg: 'Source: Portal Inquiry',
      callbacks: 2,
      bookingInquiries: 1,
      totalLeads: 1,
      demandScore: 79,
      status: 'Floorplan Review',
      statusType: 'neutral',
      image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
    },
  ],
  booking_inquiries: [
    {
      id: 'BK-1',
      name: 'Arthur Sterling VIP Preview Tour',
      developer: 'Azure Marina Waterfront #Penthouse 01',
      location: 'Marina Bay Promenade',
      priceRange: '$5.80M (Cash Option)',
      priceAvg: 'Scheduled: Aug 28, 11:00 AM',
      callbacks: 4,
      bookingInquiries: 148,
      totalLeads: 560,
      demandScore: 98,
      status: 'VIP Suite Confirmed',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'BK-2',
      name: 'Marcus & Sophia Site Walkthrough',
      developer: 'Highland Serenade Villa 8',
      location: 'Highland Hills',
      priceRange: '$3.10M Villa Lot',
      priceAvg: 'Scheduled: Aug 28, 2:30 PM',
      callbacks: 5,
      bookingInquiries: 86,
      totalLeads: 310,
      demandScore: 92,
      status: 'Limo Pick-up Confirmed',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'BK-3',
      name: 'Elena Rostova Smart Demo Unit',
      developer: 'Nexus Silicon Tech Enclave #405',
      location: 'Tech Corridor Innovation District',
      priceRange: '$950K Smart Home',
      priceAvg: 'Scheduled: Aug 29, 10:00 AM',
      callbacks: 3,
      bookingInquiries: 125,
      totalLeads: 490,
      demandScore: 89,
      status: 'Showroom Scheduled',
      statusType: 'info',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'BK-4',
      name: 'David Henderson Sky Deck Tour',
      developer: 'The Sovereign Sky Residences #38A',
      location: 'Downtown Financial Hub',
      priceRange: '$2.10M High-Floor',
      priceAvg: 'Scheduled: Aug 30, 4:00 PM',
      callbacks: 2,
      bookingInquiries: 112,
      totalLeads: 418,
      demandScore: 94,
      status: 'Appointed with Senior Director',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=120&auto=format&fit=crop&q=80',
    },
  ],
  call_inquiries: [
    {
      id: 'CALL-1',
      name: 'Institutional Fund Portfolio Desk',
      developer: 'Apex Waterfront & Vanguard Sky',
      location: 'Marina Bay / Downtown',
      priceRange: 'Est. Inquiry: $15M Bulk',
      priceAvg: 'Call Duration: 24 mins',
      callbacks: 6,
      bookingInquiries: 2,
      totalLeads: 8,
      demandScore: 97,
      status: 'Follow-up Call Scheduled',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'CALL-2',
      name: 'Tech Founder Relocation Inquiry',
      developer: 'Nexus Silicon Tech Enclave',
      location: 'Tech Corridor Innovation District',
      priceRange: 'Est. Inquiry: $1.8M Duplex',
      priceAvg: 'Call Duration: 16 mins',
      callbacks: 3,
      bookingInquiries: 1,
      totalLeads: 4,
      demandScore: 89,
      status: 'Brochure Dispatched via WhatsApp',
      statusType: 'info',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    },
  ],
  deal_won: [
    {
      id: 'WON-1',
      name: 'Azure Marina Grand Penthouse 50A',
      developer: 'Apex Waterfront Estates',
      location: 'Marina Bay Promenade',
      priceRange: 'Closed: $5,250,000',
      priceAvg: 'Commission: $105,000 (2%)',
      callbacks: 12,
      bookingInquiries: 4,
      totalLeads: 1,
      demandScore: 99,
      status: 'Contract Signed & 10% Escrow Deposited',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'WON-2',
      name: 'The Sovereign Sky Executive Residence 22C',
      developer: 'Vanguard Realty Group',
      location: 'Downtown Financial Hub',
      priceRange: 'Closed: $2,180,000',
      priceAvg: 'Commission: $43,600 (2%)',
      callbacks: 8,
      bookingInquiries: 3,
      totalLeads: 1,
      demandScore: 96,
      status: 'Deed Registered & Closed',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=120&auto=format&fit=crop&q=80',
    },
  ],
  deal_lost: [
    {
      id: 'LOST-1',
      name: 'Highland Serenade Ridge Villa 3',
      developer: 'Elysian Living Corp',
      location: 'Highland Hills',
      priceRange: 'Lost Value: $3,400,000',
      priceAvg: 'Reason: Bank Mortgage Loan Rejection',
      callbacks: 9,
      bookingInquiries: 3,
      totalLeads: 1,
      demandScore: 72,
      status: 'Contract Lapsed - Unit Relisted',
      statusType: 'danger',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LOST-2',
      name: 'Nexus Silicon Commercial Bay 2',
      developer: 'InnoUrban Developments',
      location: 'Tech Corridor Innovation District',
      priceRange: 'Lost Value: $1,250,000',
      priceAvg: 'Reason: Selected Competitor Park',
      callbacks: 6,
      bookingInquiries: 2,
      totalLeads: 1,
      demandScore: 68,
      status: 'Lost to Competitor District',
      statusType: 'danger',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    },
  ],
  follow_ups: [
    {
      id: 'FOL-1',
      name: 'Elena Rostova Term-Sheet Revisions',
      developer: 'InnoUrban Developments',
      location: 'Tech Corridor Innovation District',
      priceRange: 'Value: $950K Smart Home',
      priceAvg: 'Due: Today at 4:30 PM',
      callbacks: 4,
      bookingInquiries: 1,
      totalLeads: 1,
      demandScore: 93,
      status: 'Discount Clause Under Review',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'FOL-2',
      name: 'Amira Al-Mansoor Institutional NDA',
      developer: 'Apex Waterfront Estates',
      location: 'Marina Bay Promenade',
      priceRange: 'Value: $12.0M Institutional',
      priceAvg: 'Due: Tomorrow 10:00 AM',
      callbacks: 6,
      bookingInquiries: 2,
      totalLeads: 1,
      demandScore: 99,
      status: 'Legal Counsel Reviewing Escrow Terms',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    },
  ],
  conversion_rate: [
    {
      id: 'CONV-1',
      name: 'Azure Marina Waterfront',
      developer: 'Apex Waterfront Estates',
      location: 'Marina Bay Promenade',
      priceRange: '$1.20M - $5.80M',
      priceAvg: 'Conversion: 9.8% (Top Leader)',
      callbacks: 260,
      bookingInquiries: 148,
      totalLeads: 560,
      demandScore: 98,
      status: 'Exceeding Benchmark (+2.4%)',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'CONV-2',
      name: 'The Sovereign Sky Residences',
      developer: 'Vanguard Realty Group',
      location: 'Downtown Financial Hub',
      priceRange: '$850.0K - $3.40M',
      priceAvg: 'Conversion: 8.6% (Healthy)',
      callbacks: 195,
      bookingInquiries: 112,
      totalLeads: 418,
      demandScore: 96,
      status: 'On Target',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'CONV-3',
      name: 'Highland Serenade Villas',
      developer: 'Elysian Living Corp',
      location: 'Highland Hills',
      priceRange: '$2.10M - $6.50M',
      priceAvg: 'Conversion: 7.9%',
      callbacks: 140,
      bookingInquiries: 86,
      totalLeads: 310,
      demandScore: 91,
      status: 'Stable Funnel',
      statusType: 'info',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'CONV-4',
      name: 'Nexus Silicon Tech Enclave',
      developer: 'InnoUrban Developments',
      location: 'Tech Corridor Innovation District',
      priceRange: '$420.0K - $1.10M',
      priceAvg: 'Conversion: 8.2%',
      callbacks: 220,
      bookingInquiries: 125,
      totalLeads: 490,
      demandScore: 88,
      status: 'Above Average',
      statusType: 'success',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    },
  ],
  low_demand_projects: [
    {
      id: 'LDP-1',
      name: 'Heritage Stone Eco Village',
      developer: 'Greenstone Developers',
      location: 'Greenwood Valley Reserve',
      priceRange: '$650.0K - $1.40M',
      priceAvg: 'Avg $640/sq.ft',
      callbacks: 54,
      bookingInquiries: 22,
      totalLeads: 94,
      demandScore: 66,
      status: 'Needs Marketing Boost',
      statusType: 'danger',
      image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LDP-2',
      name: 'Eastgate Logistics Hub Commercial',
      developer: 'Apex Infrastructure Group',
      location: 'Eastgate Commercial Parkway',
      priceRange: '$1.10M - $2.80M',
      priceAvg: 'Avg $520/sq.ft',
      callbacks: 42,
      bookingInquiries: 18,
      totalLeads: 82,
      demandScore: 59,
      status: 'Campaign Optimization Needed',
      statusType: 'danger',
      image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=120&auto=format&fit=crop&q=80',
    },
    {
      id: 'LDP-3',
      name: 'Solaria Crest Townhouses Phase 2',
      developer: 'Solaria Buildcon',
      location: 'Solaria Foothills',
      priceRange: '$780.0K - $1.15M',
      priceAvg: 'Avg $710/sq.ft',
      callbacks: 48,
      bookingInquiries: 20,
      totalLeads: 86,
      demandScore: 62,
      status: 'Pricing Revision Pending',
      statusType: 'warning',
      image: 'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=120&auto=format&fit=crop&q=80',
    },
  ],
};

// =========================================================================
// FUNNEL & WISHLIST DATA
// =========================================================================

export const FUNNEL_STEPS: FunnelStep[] = [
  {
    id: 1,
    title: 'Total Leads Captured',
    subtitle: 'Initial inquiries across web, ads, calls & portals',
    value: 2100,
    totalPercentage: '100% total',
    retentionRate: undefined,
    color: '#8b181b',
  },
  {
    id: 2,
    title: 'Call Inquiries & Callbacks',
    subtitle: 'Verified phone contacts & pre-qualification dialogues',
    value: 1240,
    totalPercentage: '59% total',
    retentionRate: '59.0% retention',
    color: '#d97706',
  },
  {
    id: 3,
    title: 'Booking Inquiries & Site Visits',
    subtitle: 'VIP walkthroughs & sales gallery scheduled slots',
    value: 680,
    totalPercentage: '32.4% total',
    retentionRate: '54.8% retention',
    color: '#0284c7',
  },
  {
    id: 4,
    title: 'Active Follow-Ups & Term Sheets',
    subtitle: 'Unit reservations, floorplan options & financing review',
    value: 395,
    totalPercentage: '18.8% total',
    retentionRate: '58.1% retention',
    color: '#0d9488',
  },
  {
    id: 5,
    title: 'Deal Won & Contracts Signed',
    subtitle: 'Booking deposits cleared and final deed closure',
    value: 172,
    totalPercentage: '8.19% total',
    retentionRate: '43.5% retention',
    color: '#16a34a',
  },
];

export const WISHLIST_PROJECTS: WishlistProject[] = [
  { rank: 1, name: 'Azure Marina Waterfront', saves: 898, demandLevel: 'High Demand', maxSaves: 1000 },
  { rank: 2, name: 'Nexus Silicon Tech Enc...', saves: 738, demandLevel: 'High Demand', maxSaves: 1000 },
  { rank: 3, name: 'The Sovereign Sky Res...', saves: 648, demandLevel: 'High Demand', maxSaves: 1000 },
  { rank: 4, name: 'Highland Serenade Vill...', saves: 512, demandLevel: 'High Demand', maxSaves: 1000 },
  { rank: 5, name: 'Uptown Royale Boulev...', saves: 210, demandLevel: 'Moderate Demand', maxSaves: 1000 },
  { rank: 6, name: 'Heritage Stone Eco Vil...', saves: 94, demandLevel: 'Low Demand', maxSaves: 1000 },
];
